
list(APPEND PUBLIC_HEADERS
  # General headers
  BoundsCuller.h
  DrawParams.h
  EdlEffect.h
  FboEffect.h
  FramesPerSecondWindow.h
  FrameStamp.h
  Magnum.h
  MagnumColour.h
  MagnumV3.h
  ThirdEyeScene.h
  ViewableWindow.h
  Viewer.h
  camera/Camera.h
  camera/Controller.h
  camera/Fly.h
  data/DataThread.h
  data/NetworkThread.h
  data/StreamThread.h
  handler/Camera.h
  handler/Category.h
  handler/MeshResource.h
  handler/MeshSet.h
  handler/MeshShape.h
  handler/Message.h
  handler/Shape.h
  handler/Text2d.h
  handler/Text3d.h
  painter/ShapeCache.h
  painter/ShapePainter.h
  painter/Arrow.h
  painter/Box.h
  painter/Capsule.h
  painter/Cone.h
  painter/Cylinder.h
  painter/Plane.h
  painter/Pose.h
  painter/Sphere.h
  painter/Star.h
  painter/Text.h
  mesh/Converter.h
  shaders/Edl.h
  shaders/Flat.h
  shaders/PointGeom.h
  shaders/Pvm.h
  shaders/Shader.h
  shaders/ShaderLibrary.h
  shaders/VertexColour.h
  shaders/VoxelGeom.h
  util/Enum.h
  util/ResourceList.h
)

list(APPEND SOURCES
  BoundsCuller.cpp
  EdlEffect.cpp
  FboEffect.cpp
  FramesPerSecondWindow.cpp
  FrameStamp.cpp
  ThirdEyeScene.cpp
  Viewer.cpp
  camera/Camera.cpp
  camera/Controller.cpp
  camera/Fly.cpp
  data/DataThread.cpp
  data/NetworkThread.cpp
  data/StreamThread.cpp
  handler/Camera.cpp
  handler/Category.cpp
  handler/MeshResource.cpp
  handler/MeshSet.cpp
  handler/MeshShape.cpp
  handler/Message.cpp
  handler/Shape.cpp
  handler/Text2d.cpp
  handler/Text3d.cpp
  painter/ShapeCache.cpp
  painter/ShapePainter.cpp
  painter/Arrow.cpp
  painter/Box.cpp
  painter/Capsule.cpp
  painter/Cone.cpp
  painter/Cylinder.cpp
  painter/Plane.cpp
  painter/Pose.cpp
  painter/Sphere.cpp
  painter/Star.cpp
  painter/Text.cpp
  mesh/Converter.cpp
  shaders/Edl.cpp
  shaders/Edl.frag
  shaders/Edl.vert
  shaders/Flat.cpp
  shaders/Point.frag
  shaders/Point.geom
  shaders/Point.vert
  shaders/PointGeom.cpp
  shaders/Shader.cpp
  shaders/ShaderLibrary.cpp
  shaders/VertexColour.cpp
  shaders/Voxel.frag
  shaders/Voxel.geom
  shaders/Voxel.vert
  shaders/Voxelgeom.cpp
  util/ResourceList.cpp
)

list(APPEND PRIVATE_SOURCES
)
